/// Flutter icons Attention
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Attention
///      fonts:
///       - asset: fonts/Attention.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Attention {
  Attention._();

  static const _pFontFam = 'Attention'; // Reconhece a fonte declarada no pubspec.yaml

  static const IconData attention__1_ = const IconData(0xe803, fontFamily: _pFontFam); //Indica o icone da fonte que sera utilizada
}
